import React,{useEffect,useMemo,useState}from'react';
import{createRoot}from'react-dom/client';
import{Activity,CalendarDays,Database,Goal,Search,ShieldCheck,Trophy,RefreshCw,Star,CheckCircle2,AlertTriangle,XCircle,BarChart3,BookOpen,TrendingUp}from'lucide-react';
import'./style.css';

const today=()=>new Date().toLocaleDateString('en-CA');
const fmt=v=>v===null||v===undefined||Number.isNaN(v)?'—':v;
const statusLabel=s=>s==='PREMIUM'?'⭐⭐⭐ PREMIUM':s==='WATCH'?'⭐⭐ À SURVEILLER':'❌ REJETÉ';
const statusIcon=s=>s==='PREMIUM'?<CheckCircle2/>:s==='WATCH'?<AlertTriangle/>:<XCircle/>;
const clamp=(x,a,b)=>Math.max(a,Math.min(b,x));

function sampleLabel(n){if(n<30)return'DONNÉES INSUFFISANTES';if(n<100)return'TENDANCE PRÉLIMINAIRE';if(n<500)return'ÉVALUATION UTILE';return'ÉCHANTILLON SOLIDE'}
function calibrationMetrics(ledger){
 const settled=ledger.filter(x=>['WIN','LOSS'].includes(x.result)&&Number.isFinite(Number(x.modelProbability)));
 const n=settled.length;if(!n)return{n:0,wins:0,accuracy:null,brier:null,logLoss:null,bins:[]};
 let wins=0,brier=0,ll=0;const bins=new Map();
 for(const x of settled){const y=x.result==='WIN'?1:0,p=clamp(Number(x.modelProbability)/100,.001,.999);wins+=y;brier+=(p-y)**2;ll+=-(y*Math.log(p)+(1-y)*Math.log(1-p));const lo=Math.floor(Number(x.modelProbability)/5)*5,k=`${lo}-${lo+5}`;const z=bins.get(k)||{lo,n:0,sumP:0,w:0};z.n++;z.sumP+=Number(x.modelProbability);z.w+=y;bins.set(k,z)}
 return{n,wins,accuracy:+(100*wins/n).toFixed(1),brier:+(brier/n).toFixed(3),logLoss:+(ll/n).toFixed(3),bins:[...bins.values()].sort((a,b)=>a.lo-b.lo).map(z=>({...z,announced:+(z.sumP/z.n).toFixed(1),real:+(100*z.w/z.n).toFixed(1)}))};
}
function marketProbability(g,key){const v=g?.synthesis?.oneXtwo?.[key];return Number.isFinite(Number(v))?+Number(v).toFixed(1):null}
function modelPick(analysis){if(!analysis?.probabilities)return null;const xs=[['home',analysis.probabilities.home],['draw',analysis.probabilities.draw],['away',analysis.probabilities.away]].filter(x=>Number.isFinite(Number(x[1])));xs.sort((a,b)=>b[1]-a[1]);return xs[0]?{key:xs[0][0],prob:+xs[0][1]}:null}

function ScorerCard({x,onTrack,tracked}){
 return <article className={`scorerCard scorer-${x.status.toLowerCase()}`}><div className="scorerHead"><div className="playerIdentity">{x.photo&&<img src={x.photo} alt=""/>}<div><h4>{x.player}</h4><p>{x.teamName} · {x.side==='home'?'Domicile':'Extérieur'} · {x.position||'poste non fourni'}</p></div></div><div className={`scorerStatus ${x.status}`}>{statusIcon(x.status)} {statusLabel(x.status)}</div></div>
 <div className="scoreStrip"><div><strong>{x.indispensableScore}</strong><span>Indispensable /100</span></div><div><strong>{x.formContextScore}</strong><span>Forme & contexte /100</span></div><div><strong>{x.dataCompleteness}%</strong><span>Données complètes</span></div></div>
 <div className="factorGrid"><div><span>Titularisations saison</span><b>{fmt(x.startsPct)}{x.startsPct!=null?'%':''}</b></div><div><span>Minutes moy. · 5 derniers</span><b>{fmt(x.recent?.minutesAvg)}{x.recent?.minutesAvg!=null?"'":''}</b></div><div><span>Titulaire · 5 derniers</span><b>{fmt(x.recent?.starts)}/{fmt(x.recent?.matches)}</b></div><div><span>Sortie avant 70'</span><b>{fmt(x.recent?.earlySubPct)}{x.recent?.earlySubPct!=null?'%':''}</b></div><div><span>Buts · 5 derniers</span><b>⚽ {fmt(x.recent?.goals)}</b></div><div><span>Buts · 5 {x.side==='home'?'domicile':'extérieur'}</span><b>⚽ {fmt(x.venue?.goals)}</b></div><div><span>Tirs cadrés /90</span><b>{fmt(x.recent?.shotsOnTarget90)}</b></div><div><span>Part des buts équipe</span><b>{fmt(x.goalShare)}{x.goalShare!=null?'%':''}</b></div><div><span>Concurrence / rotation</span><b>{fmt(x.rotationRisk)}</b></div><div><span>Penalty</span><b>{x.penaltyRole==='PROBABLE'?'✅ probable':'— non identifié'}</b></div><div><span>Défense adverse</span><b>{fmt(x.opponentDefence?.grade)} · {fmt(x.opponentDefence?.goalsAgainstAvg)} BC/m</b></div><div><span>XI officiel</span><b>{x.lineupStatus==='CONFIRMED_STARTER'?'✅ titulaire':x.lineupStatus==='CONFIRMED_BENCH'?'❌ banc':'⏳ attente'}</b></div><div><span>Santé</span><b>{x.healthStatus==='OK'?'✅ disponible':'🚑 indisponible'}</b></div><div><span>Cote buteur actuelle</span><b>{x.market?.available?`${x.market.current} · ${x.market.bookmakers} book(s)`:'— fournisseur non disponible'}</b></div><div><span>Probabilité buteur</span><b>— tant que non calibrée</b></div><div><span>xG joueur</span><b>— si non fourni</b></div></div>
 <p className="scorerReason">{x.reason}</p>{x.status==='PREMIUM'&&<button className="trackBtn" onClick={()=>onTrack(x)} disabled={tracked}>{tracked?'✓ Signal suivi':'＋ Suivre ce signal'}</button>}</article>
}
function ScorerBoard({data,loading,onTrack,ledger}){
 if(loading)return <div className="premiumLoading"><RefreshCw className="spin"/><div><b>Analyse Buteur Premium…</b><p>Usage, forme récente, domicile/extérieur, défense adverse, blessures et XI.</p></div></div>;
 if(!data)return <div className="premiumEmpty">Sélectionne un match pour lancer le filtre Buteur Premium.</div>;
 if(!data.available)return <div className="premiumUnavailable"><ShieldCheck/><div><b>Module installé — données joueur non disponibles</b><p>{data.message||data.error}. Aucun buteur artificiel n’est créé.</p></div></div>;
 const all=[...(data.candidates?.home||[]),...(data.candidates?.away||[])],premium=all.filter(x=>x.status==='PREMIUM'),watch=all.filter(x=>x.status==='WATCH'),rejected=all.filter(x=>x.status==='REJECTED');
 return <div className="premiumBoard"><div className="premiumSummary"><div><small>Résultat</small><strong>{premium.length?`${premium.length} PREMIUM`:'AUCUN PREMIUM'}</strong><span>{data.lineupsConfirmed?'XI confirmés':'XI pas encore tous confirmés'}</span></div><div><small>Candidats</small><strong>{all.length}</strong><span>{watch.length} surveiller · {rejected.length} rejetés</span></div><div><small>Appels source</small><strong>{fmt(data.callsEstimated)}</strong><span>à la demande</span></div><div><small>Règle</small><strong>STRICTE</strong><span>Aucun joueur forcé</span></div></div>{!premium.length&&<div className="noPremium">🚫 Aucun buteur ne passe actuellement tous les filtres Premium.</div>}<div className="scorerList">{all.map(x=><ScorerCard key={`${x.teamId}-${x.playerId}`} x={x} onTrack={onTrack} tracked={ledger.some(l=>l.fixtureId===data.fixture.id&&l.playerId===x.playerId)}/>)}</div><div className="methodNote"><b>Important :</b> les notes /100 sont des filtres internes, pas une probabilité de marquer. {data.limitations?.join(' · ')}</div></div>
}

function CommentaryBlock({data,loading}){
 if(loading)return <div className="commentaryBox loading"><BookOpen/><div><b>Commentaire du match…</b><p>Marché Pronosoft, puis forme / absences / XI si API-Football est connecté.</p></div></div>;
 if(!data)return null;
 return <div className="commentaryBox"><div className="commentaryHead"><div><small>💬 COMMENTAIRE BET ANALYTICS</small><b>{data.depth==='ENRICHED'?'ANALYSE ENRICHIE':'ANALYSE MARCHÉ'}</b></div><span>{data.source||'BET ANALYTICS'}</span></div><p>{data.commentary||'Commentaire indisponible.'}</p>{data.warning&&<div className="commentaryWarn">⚠️ {data.warning}</div>}{data.limitations?.length>0&&<small className="commentaryLimit">{data.limitations.join(' · ')}</small>}</div>
}

function Calibration({ledger}){
 const m=calibrationMetrics(ledger);const scorers=ledger.filter(x=>x.type==='scorer'&&['WIN','LOSS'].includes(x.result));const sw=scorers.filter(x=>x.result==='WIN').length;
 return <section className="calibrationPage"><div className="sectionHead"><div><p className="eyebrow">VALIDATION DU MODÈLE</p><h2>Calibration & historique</h2></div><span className={`confidence ${m.n<30?'low':'ok'}`}>{sampleLabel(m.n)}</span></div>
 <div className="calKpis"><div><strong>{m.wins}/{m.n||0}</strong><span>bons gagnants désignés</span></div><div><strong>{m.accuracy==null?'—':`${m.accuracy}%`}</strong><span>taux de réussite</span></div><div><strong>{m.brier??'—'}</strong><span>Score de Brier · 0 = parfait</span></div><div><strong>{m.logLoss??'—'}</strong><span>Log loss</span></div></div>
 {m.n<30&&<div className="notice warning"><b>Échantillon insuffisant.</b> Les chiffres sont affichés, mais BET ANALYTICS ne considère pas le modèle validé avant au moins 30 prédictions réglées.</div>}
 <div className="panelBlock"><h3>Calibrage — un « X % » gagne-t-il réellement X % ?</h3>{m.bins.length?m.bins.map(b=><div className={`calRow ${Math.abs(b.announced-b.real)<=6?'good':'bad'}`} key={b.lo}><b>favori {b.lo}–{b.lo+5}%</b><span>annoncé {b.announced}% → réalisé {b.real}%</span><em>{b.n} match{b.n>1?'s':''}</em></div>):<p className="muted">Aucune prédiction probabiliste réglée pour l’instant.</p>}<p className="muted">Vert : écart ≤ 6 points. Rouge : sur- ou sous-confiance. Les petites cases avec peu de matchs restent très instables.</p></div>
 <div className="panelBlock"><h3>Buteurs Premium</h3><div className="calKpis compact"><div><strong>{scorers.length}</strong><span>signaux réglés</span></div><div><strong>{scorers.length?`${(100*sw/scorers.length).toFixed(1)}%`:'—'}</strong><span>ont marqué</span></div><div><strong>—</strong><span>Brier indisponible tant qu’une vraie probabilité buteur calibrée n’existe pas</span></div></div></div></section>
}

function Journal({ledger,onSettle,onClosing}){return <section className="calibrationPage"><div className="sectionHead"><div><p className="eyebrow">JOURNAL IMMUTABLE CÔTÉ UTILISATEUR</p><h2>Signaux enregistrés avant match</h2></div><span>{ledger.length} signal(s)</span></div>{!ledger.length?<div className="notice">Aucun signal suivi.</div>:<div className="journalTable">{ledger.map(x=><div className="journalRow" key={x.id}><div><b>{x.player||x.pickLabel}</b><small>{x.match} · {x.type==='scorer'?'Buteur Premium':'Gagnant modèle'}</small></div><span>Modèle {x.modelProbability!=null?`${x.modelProbability}%`:'—'}</span><span>Marché {x.marketProbability!=null?`${x.marketProbability}%`:'—'}</span><span>Cote {x.odd??'—'} → {x.closingOdd??'—'}</span><span className={`result ${x.result}`}>{x.result==='PENDING'?'⏳ EN ATTENTE':x.result==='WIN'?'✅ GAGNÉ':'❌ PERDU'}</span><div className="settleBtns">{x.result==='PENDING'&&<><button onClick={()=>onSettle(x.id,'WIN')}>✅</button><button onClick={()=>onSettle(x.id,'LOSS')}>❌</button></>}<button onClick={()=>onClosing(x.id)}>Closing</button></div></div>)}</div>}</section>}

function App(){
 const[date,setDate]=useState(today()),[fixtures,setFixtures]=useState([]),[catalog,setCatalog]=useState([]),[sourceInfo,setSourceInfo]=useState(null),[loading,setLoading]=useState(true),[error,setError]=useState('');
 const[q,setQ]=useState(''),[leagueFilter,setLeagueFilter]=useState('ALL'),[analysisMode,setAnalysisMode]=useState('goals'),[selected,setSelected]=useState(null),[view,setView]=useState('dashboard');
 const[analysis,setAnalysis]=useState(null),[analysisLoading,setAnalysisLoading]=useState(false),[scorers,setScorers]=useState(null),[scorerLoading,setScorerLoading]=useState(false);
 const[commentary,setCommentary]=useState(null),[commentaryLoading,setCommentaryLoading]=useState(false),[autoDateDone,setAutoDateDone]=useState(false);
 const[ledger,setLedger]=useState(()=>{try{const v=JSON.parse(localStorage.getItem('ba-v29-ledger')||localStorage.getItem('ba-v24-ledger')||'[]');if(v.length)return v;const old=JSON.parse(localStorage.getItem('ba-scorer-ledger')||'[]');return old.map(x=>({...x,type:'scorer',modelProbability:null,marketProbability:null}))}catch{return[]}});
 const saveLedger=next=>{setLedger(next);localStorage.setItem('ba-v29-ledger',JSON.stringify(next))};

 async function load(){setLoading(true);setError('');try{
   const [r,lr]=await Promise.all([fetch(`/api/football?date=${date}&debug=1&_=${Date.now()}`,{cache:'no-store'}),fetch('/api/leagues',{cache:'no-store'}).catch(()=>null)]);
   const d=await r.json();if(!r.ok)throw new Error(d.error||'Erreur API');
   if(lr?.ok){const lj=await lr.json();setCatalog((lj.leagues||[]).map(x=>x.name||x))}
   setSourceInfo({availableDates:d.availableDates||[],parserVersion:d.parserVersion,sourceStatus:d.sourceStatus,source:d.source});
   if(!autoDateDone&&(d.results??0)===0&&d.availableDates?.length&&!d.availableDates.includes(date)){const next=d.availableDates.find(x=>x>=date)||d.availableDates[0];if(next&&next!==date){setAutoDateDone(true);setDate(next);return}}
   setFixtures((d.fixtures||[]).map(m=>({...m,feedSources:m.feedSources||['Pronosoft']})));
 }catch(e){setError(e.message)}finally{setLoading(false)}}
 useEffect(()=>{load()},[date]);

 async function openMatch(g){
  setSelected(g);setAnalysis(null);setScorers(null);setCommentary(null);setAnalysisLoading(analysisMode!=='scorer');setScorerLoading(analysisMode==='scorer'||analysisMode==='winner');setCommentaryLoading(true);
  const md=(g.date||date).slice(0,10),qs=new URLSearchParams({home:g.home.name,away:g.away.name,date:md,league:g.league?.name||'',oh:g.odds?.home||'',od:g.odds?.draw||'',oa:g.odds?.away||''});
  const jobs=[fetch(`/api/match-commentary?${qs}`).then(r=>r.json()).catch(e=>({available:false,commentary:'Commentaire indisponible.',warning:e.message}))];
  if(analysisMode!=='scorer')jobs.push(fetch(`/api/match-analysis?homeName=${encodeURIComponent(g.home.name)}&awayName=${encodeURIComponent(g.away.name)}&date=${md}`).then(r=>r.json()).catch(e=>({error:e.message})));
  if(analysisMode==='scorer'||analysisMode==='winner')jobs.push(fetch(`/api/scorer-premium?home=${encodeURIComponent(g.home.name)}&away=${encodeURIComponent(g.away.name)}&date=${md}`).then(r=>r.json()).catch(e=>({available:false,error:e.message})));
  const out=await Promise.all(jobs);setCommentary(out[0]);let idx=1;if(analysisMode!=='scorer'){setAnalysis(out[idx++]);}if(analysisMode==='scorer'||analysisMode==='winner'){setScorers(out[idx]);}
  setCommentaryLoading(false);setAnalysisLoading(false);setScorerLoading(false)
 }
 async function loadScorers(){if(!selected)return;setScorerLoading(true);try{const md=(selected.date||date).slice(0,10),r=await fetch(`/api/scorer-premium?home=${encodeURIComponent(selected.home.name)}&away=${encodeURIComponent(selected.away.name)}&date=${md}`);setScorers(await r.json())}catch(e){setScorers({available:false,error:e.message})}finally{setScorerLoading(false)}}
 function trackScorer(x){if(!scorers?.fixture)return;const item={id:`scorer-${scorers.fixture.id}-${x.playerId}`,type:'scorer',fixtureId:scorers.fixture.id,date:scorers.fixture.date,match:`${scorers.fixture.home.name} - ${scorers.fixture.away.name}`,playerId:x.playerId,player:x.player,status:x.status,odd:x.market?.current??null,modelProbability:null,marketProbability:x.market?.current?+(100/x.market.current).toFixed(1):null,result:'PENDING',createdAt:new Date().toISOString()};saveLedger([item,...ledger.filter(z=>z.id!==item.id)].slice(0,500))}
 function trackWinner(){const p=modelPick(analysis);if(!p||!selected)return;const label=p.key==='home'?selected.home.name:p.key==='away'?selected.away.name:'Match nul',mp=marketProbability(selected,p.key);const odd=mp?+(100/mp).toFixed(2):null;const item={id:`winner-${selected.id}-${p.key}`,type:'winner',fixtureId:selected.id,date:selected.date,match:`${selected.home.name} - ${selected.away.name}`,pick:p.key,pickLabel:label,modelProbability:p.prob,marketProbability:mp,odd,result:'PENDING',createdAt:new Date().toISOString()};saveLedger([item,...ledger.filter(z=>z.id!==item.id)].slice(0,500))}
 function settle(id,result){saveLedger(ledger.map(x=>x.id===id?{...x,result,settledAt:new Date().toISOString()}:x))}
 function closing(id){const x=ledger.find(z=>z.id===id),v=prompt('Cote closing (laisser vide pour annuler)',x?.closingOdd??'');if(v===null||v==='')return;const n=Number(String(v).replace(',','.'));if(Number.isFinite(n)&&n>1)saveLedger(ledger.map(z=>z.id===id?{...z,closingOdd:n}:z))}

 const leagues=useMemo(()=>[...new Set(fixtures.map(g=>g.league?.name).filter(Boolean))].sort((a,b)=>a.localeCompare(b,'tr')),[fixtures]);
 const filtered=useMemo(()=>fixtures.filter(g=>`${g.home?.name||''} ${g.away?.name||''} ${g.league?.name||''}`.toLowerCase().includes(q.toLowerCase())).filter(g=>leagueFilter==='ALL'||g.league?.name===leagueFilter),[fixtures,q,leagueFilter]);
 const goalScore=g=>{const o=Number(g.odds?.over25),u=Number(g.odds?.under25);if(o>1&&u>1){const a=1/o,b=1/u;return +(100*a/(a+b)).toFixed(1)}return null},winnerScore=g=>Math.max(g.synthesis?.oneXtwo?.home??0,g.synthesis?.oneXtwo?.away??0);
 const displayed=useMemo(()=>[...filtered].sort((a,b)=>analysisMode==='goals'?(goalScore(b)??-1)-(goalScore(a)??-1):analysisMode==='winner'?winnerScore(b)-winnerScore(a):0),[filtered,analysisMode]);
 const cm=calibrationMetrics(ledger);

 return <div className="app"><aside><div className="brand"><div className="mark">BA</div><div><b>BET ANALYTICS</b><small>SPORTS INTELLIGENCE</small></div></div><nav><a className={view==='dashboard'?'active':''} onClick={()=>setView('dashboard')}><Activity/>Dashboard</a><a onClick={()=>{setView('dashboard');setAnalysisMode('scorer')}}><Trophy/>Buteurs Premium</a><a className={view==='calibration'?'active':''} onClick={()=>setView('calibration')}><BarChart3/>Calibration</a><a className={view==='journal'?'active':''} onClick={()=>setView('journal')}><Database/>Journal <small>{ledger.length}</small></a></nav><div className="api"><ShieldCheck/><div><b>Données vérifiées</b><small>Jamais remplacées par une estimation</small></div></div></aside>
 <main><header><div><p className="eyebrow">BET ANALYTICS V29 · PRONOSOFT + COMMENTAIRES + BUTEURS PREMIUM</p><h1>{view==='dashboard'?'Match Intelligence':view==='calibration'?'Model Validation':'Journal'}</h1><p className="muted">Pronosoft pour le programme et le marché; commentaire par match; API-Football optionnel pour forme, absences, XI et joueurs. Données manquantes explicitement signalées.</p></div>{view==='dashboard'&&<label className="date"><CalendarDays/><input type="date" value={date} onChange={e=>setDate(e.target.value)}/></label>}</header>
 {view==='calibration'?<Calibration ledger={ledger}/>:view==='journal'?<Journal ledger={ledger} onSettle={settle} onClosing={closing}/>:<>
 <section className="stats"><div><small>Matchs majeurs hommes</small><strong>{displayed.length}</strong><span>{date}</span></div><div><small>Signaux suivis</small><strong>{ledger.length}</strong><span>{cm.n} réglés probabilistes</span></div><div><small>Calibration</small><strong>{cm.brier??'—'}</strong><span>Brier · {sampleLabel(cm.n)}</span></div><div><small>Parser ligues</small><strong>V29</strong><span>Pronosoft + commentaire par match</span></div></section>
 <div className="toolbar"><div className="tabs"><button className="on">Football</button><button disabled>NHL bientôt</button><button disabled>MLB bientôt</button></div><label><Search/><input value={q} onChange={e=>setQ(e.target.value)} placeholder="Équipe ou championnat"/></label><button className="reload" onClick={load}><RefreshCw/> Actualiser</button></div>
 <div className="leagueTitle"><b>Ligues hommes majeures</b><span>Premières divisions + grandes compétitions continentales. Féminin, jeunes, réserves, D2 et amicaux exclus.</span></div>
 <div className="leaguebar"><button className={leagueFilter==='ALL'?'active':''} onClick={()=>setLeagueFilter('ALL')}>Toutes · {fixtures.length}</button>{leagues.map(l=><button key={l} className={leagueFilter===l?'active':''} onClick={()=>setLeagueFilter(l)}>{l} · {fixtures.filter(g=>g.league?.name===l).length}</button>)}</div>
 <details className="catalog"><summary><b>{catalog.length||'—'} ligues/compétitions majeures prises en charge</b> · afficher le catalogue</summary><div>{catalog.map(x=><span key={x}>{x}</span>)}</div></details>
 {sourceInfo?.availableDates?.length>0&&!sourceInfo.availableDates.includes(date)&&<div className="notice warning"><b>Aucun programme Pronosoft trouvé exactement pour {date}.</b> Dates présentes dans la source : {sourceInfo.availableDates.slice(0,8).join(', ')}. Le site n’attribue plus artificiellement une mauvaise date aux matchs.</div>}
 <div className="modebar"><button className={analysisMode==='goals'?'active':''} onClick={()=>setAnalysisMode('goals')}>🔥 Matchs à buts</button><button className={analysisMode==='winner'?'active':''} onClick={()=>setAnalysisMode('winner')}>🏆 Gagnants</button><button className={analysisMode==='scorer'?'active scorerMode':''} onClick={()=>setAnalysisMode('scorer')}>⭐ Buteurs indispensables</button><span>{analysisMode==='scorer'?'Premium = XI officiel + filtres stricts':'Modèle + marché + historique'}</span></div>
 <div className="sectionHead"><h2>{analysisMode==='scorer'?'Matchs à analyser pour les buteurs':'Programme'}</h2><span>{loading?'Chargement…':`${displayed.length} matchs`}</span></div>{error&&<div className="notice"><b>Programme :</b> {error}</div>}
 <div className="grid">{displayed.map(g=>{const dt=g.date?new Date(g.date):null;return <article className={`card ${analysisMode==='scorer'?'scorerMatch':''}`} key={g.id} onClick={()=>openMatch(g)}><div className="league"><span>{g.league?.name}</span><b>{dt&&!Number.isNaN(dt)?dt.toLocaleTimeString('fr-CH',{hour:'2-digit',minute:'2-digit'}):g.time}</b></div><div className="feedbadge">{(g.feedSources||[g.source]).filter(Boolean).join(' + ')}</div><div className="teams"><h3>{g.home.name}</h3><span>VS</span><h3>{g.away.name}</h3></div>{analysisMode==='goals'&&goalScore(g)!=null&&<div className="goalbadge">🔥 +2,5 : {goalScore(g)}% marché sans marge</div>}{analysisMode==='winner'&&g.synthesis?.oneXtwo&&<div className="goalbadge">🏆 Marché sans marge · max {winnerScore(g).toFixed(1)}%</div>}{analysisMode==='scorer'&&<div className="premiumTeaser"><Star/><div><b>Rechercher les buteurs indispensables</b><span>Forme 5 · lieu · minutes · rotation · blessures · XI</span></div></div>}<button className="detail">{analysisMode==='scorer'?'Analyser les buteurs':'Analyse + commentaire'}</button></article>})}</div>{!loading&&!displayed.length&&<div className="notice"><b>Aucun match majeur homme accepté pour cette date.</b> Cela peut vouloir dire qu’il n’y en a pas dans le programme source, ou que Pronosoft ne publie pas cette date dans la liste actuelle.</div>}
 <div className="notice"><b>Principe V29 :</b> Pronosoft fournit le programme et les cotes. Les commentaires sont originaux BET ANALYTICS; forme, absences, XI et buteurs utilisent API-Football uniquement si la clé est configurée.</div></>}
 </main>
 {selected&&<div className="modal" onClick={()=>setSelected(null)}><div className="panel wide" onClick={e=>e.stopPropagation()}><button className="x" onClick={()=>setSelected(null)}>×</button><p className="eyebrow">{selected.league?.name}</p><h2>{selected.home.name} <span>vs</span> {selected.away.name}</h2><p className="muted">{selected.date?new Date(selected.date).toLocaleString('fr-CH'):selected.time}</p>
 <CommentaryBlock data={commentary} loading={commentaryLoading}/>
 {analysisMode==='scorer'?<><div className="scorerHero"><div><small>MODULE BUTEUR PREMIUM</small><h3>Le buteur doit être central, durable sur le terrain et réellement difficile à remplacer.</h3></div><button onClick={loadScorers}><RefreshCw/> Relancer</button></div><ScorerBoard data={scorers} loading={scorerLoading} onTrack={trackScorer} ledger={ledger}/></>:analysisLoading?<div className="insight"><strong>Analyse en cours…</strong></div>:analysis?.error?<div className="notice"><b>{analysis.error}</b></div>:analysis?.probabilities?<><div className="modelCompare"><div><small>MODÈLE API-FOOTBALL</small><strong>{analysis.probabilities.home}% · {analysis.probabilities.draw}% · {analysis.probabilities.away}%</strong><span>xG {analysis.probabilities.expectedGoals.home} – {analysis.probabilities.expectedGoals.away}</span></div><div><small>MARCHÉ SANS MARGE</small><strong>{selected.synthesis?.oneXtwo?`${fmt(selected.synthesis.oneXtwo.home)}% · ${fmt(selected.synthesis.oneXtwo.draw)}% · ${fmt(selected.synthesis.oneXtwo.away)}%`:'—'}</strong><span>{selected.synthesis?.oneXtwo?'cotes normalisées 1X2':'marché complet indisponible'}</span></div><div><small>SIMULATION</small><strong>{analysis.simulation?`${analysis.simulation.home}% · ${analysis.simulation.draw}% · ${analysis.simulation.away}%`:'—'}</strong><span>{analysis.simulation?`${analysis.simulation.runs.toLocaleString('fr-CH')} parties simulées`:'indisponible'}</span></div><div><small>XI / JOUEURS</small><strong>{scorers?.available?(scorers.lineupsConfirmed?'✅ CONFIRMÉ':'⏳ NON CONFIRMÉ'):'—'}</strong><span>contrôle joueur séparé; pas d’ajustement inventé</span></div></div>
 <div className="prob"><div><small>Over 1.5</small><b>{analysis.probabilities.over15}%</b></div><div><small>Over 2.5</small><b>{analysis.probabilities.over25}%</b></div><div><small>Over 3.5</small><b>{analysis.probabilities.over35}%</b></div><div><small>BTTS</small><b>{analysis.probabilities.btts}%</b></div></div>
 <div className="insight"><small>MÉTHODE</small><strong>{analysis.probabilities.confidence==='standard'?'Confiance données : MOYENNE/ÉLEVÉE':'Confiance données : FAIBLE'}</strong><p>{analysis.method}</p></div>{analysisMode==='winner'&&<button className="trackBtn" onClick={trackWinner} disabled={ledger.some(x=>x.id===`winner-${selected.id}-${modelPick(analysis)?.key}`)}>{ledger.some(x=>x.id===`winner-${selected.id}-${modelPick(analysis)?.key}`)?'✓ Pronostic enregistré':`＋ Suivre le gagnant modèle · ${modelPick(analysis)?.prob??'—'}%`}</button>}</>:<div className="notice">Analyse indisponible pour ce match.</div>}
 </div></div>}</div>
}
createRoot(document.getElementById('root')).render(<App/>);
